server:
  port: 8785
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
spring:
  application:
    name: springcloud-feign

eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka
