server:
  port: 8779
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
spring:
  application:
    name: 1jiar-feign-house-ad

eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka
