server:
  port: 8767
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
spring:
  application:
    name: springcloud-feign

eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka
<<<<<<< HEAD
feign:
  hystrix:
    enabled: true
=======
>>>>>>> f4279993763febc7556e25320e911184c3ff1b9a
